### ISSUE TITLE
broken demo link

### ISSUE THREAD

**Issue by locovna** [Cirru/cirru-html#1]
Link with demos in `README.md` and repo description opens with **404 error** 😰
`See demos on http://repo.cirru.org/html`

**Comment by jiyinyiyong** [comment]
I have to say this project is already deprecated. I haven't maintained it for 3 years.

Sorry but it is deprecated. If you really want to see how it works, you have to download and compile by yourself. Ask me anything if there's errors.

Meanwhile I would suggest React for generating HTML.

**Comment by jiyinyiyong** [comment]
Well, I just want to check if it still works, anyway http://repo.cirru.org/cirru-html/

**Comment by locovna** [comment]
Ow, okay, thanks!
I just have found [pretty new project ](https://github.com/fabiomsr/from-java-to-kotlin)which use Cirru to generate html, and I completely fell in love with how it looks (and with this nice purple color in language percent line 🌸 ). Just want to see few more examples

😌

**Comment by jiyinyiyong** [comment]
Thanks. It's the first time I hear someone phrase it. You may already know that I have migrated Cirru to a graphical UI http://cirru.org/ Hope you like it also.

The old toolchains lacks maintaining. But you can ask me anything as long as I remember.

And some old projects in Cirru can be found by https://github.com/search?l=Cirru&p=1&q=stars%3A%3E%3D0&ref=advsearch&type=Repositories&utf8=%E2%9C%93
